#!/usr/bin/python

from xacro import *
import sys
from xml.dom.minidom import parseString

def replace(s, key, value):
    i = s.find(key)
    i2 = s.find('"', i+len(key)+2)
    i3 = s.find('"', i2+1)
    
    return s[:i2+1] + value + s[i3:]

def main():
    contents = open(sys.argv[1]).read()
    contents = replace(contents, 'width', sys.argv[2])
    contents = replace(contents, 'wheel_radius', sys.argv[3])
    
    doc = parseString(contents)

    process_includes(doc, os.path.dirname(sys.argv[1]))
    eval_self_contained(doc)
    banner = [xml.dom.minidom.Comment(c) for c in
              [" %s " % ('=' * 83),
               " |    This document was autogenerated by xacro from %-30s | " % sys.argv[1],
               " |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED  %-30s | " % "",
               " %s " % ('=' * 83)]]
    first = doc.firstChild
    for comment in banner:
        doc.insertBefore(comment, first)

    print doc.toprettyxml(indent='  ')
        
main()
